repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        name: mypy
        entry: mypy src/
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        args: [--config-file=pyproject.toml]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check .
        language: python
        types: [python]
        pass_filenames: true
        always_run: true
        args: ["--config=pyproject.toml", "--force-exclude"]
        exclude: |
          (?x)^(
            src/migrations/|  
            alembic.ini|    
            .venv/         
          )

  - repo: local
    hooks:
      - id: vulture
        name: vulture
        entry: vulture src/
        language: python
        types: [python]
        pass_filenames: true
        always_run: true
        additional_dependencies: [vulture]
